### ISSUE TITLE
Ripple doesn't work properly on RTL pages

### ISSUE THREAD

**Issue by itayganor** [VsevolodTrofimov/Ripple.js#11]
https://codepen.io/anon/pen/EXdyNO

It looks like a problem with the click position detection. any solution?

**Comment by v-trof** [comment]
Yes, it seems to be an issue with the `client.X`. I will fix it in 2hrs

**Comment by itayganor** [comment]
I love you. Thanks!

**Comment by v-trof** [comment]
Fixed it
Use `npm update` or get [0.4.1 release](https://github.com/VsevolodTrofimov/Ripple.js/releases/download/0.4.2/dist.zip)
